import { PluginGeneratedSdk, PluginSdkActionConfig } from '../../types';

export class PluginSdkEngine {
  /**
   * Generates production-ready TypeScript SDK and Bubble Plugin Action code
   */
  public static generatePluginSdk(config: PluginSdkActionConfig): PluginGeneratedSdk {
    const actionNameClean = config.actionName.replace(/[^a-zA-Z0-9_]/g, '');
    const isServer = config.actionType === 'server_side';

    // 1. Generate TypeScript Interfaces
    let tsInterfaces = `/**
 * TypeScript Type Definitions for Bubble.io Plugin Action
 * Action: ${config.actionName}
 * Auto-generated by Bubble Studio Plugin SDK Generator
 */

export interface ${actionNameClean}Properties {\n`;

    for (const p of config.parameters) {
      let tsType = 'string';
      if (p.type === 'number') tsType = 'number';
      else if (p.type === 'boolean') tsType = 'boolean';
      else if (p.type === 'date') tsType = 'Date | string';
      else if (p.type === 'object') tsType = 'Record<string, any>';
      else if (p.type === 'list_text') tsType = 'string[]';
      else if (p.type === 'list_number') tsType = 'number[]';
      else if (p.type === 'file') tsType = '{ filename: string; url: string; contents?: string }';

      const optional = p.required ? '' : '?';
      tsInterfaces += `  /** ${p.description || p.name} */\n  ${p.name}${optional}: ${tsType};\n`;
    }
    tsInterfaces += `}\n\n`;

    // Bubble Context interface
    tsInterfaces += `export interface ${actionNameClean}Context {\n`;
    tsInterfaces += `  keys?: Record<string, string>;\n`;
    tsInterfaces += `  currentUser?: { id: string; email?: string };\n`;
    tsInterfaces += `  request?: (options: { url: string; method?: string; headers?: Record<string, string>; body?: string }) => Promise<any>;\n`;
    tsInterfaces += `}\n\n`;

    if (config.returnsValue && config.returnFields && config.returnFields.length > 0) {
      tsInterfaces += `export interface ${actionNameClean}Response {\n`;
      for (const rf of config.returnFields) {
        let tsType = 'string';
        if (rf.type === 'number') tsType = 'number';
        else if (rf.type === 'boolean') tsType = 'boolean';
        else if (rf.type === 'date') tsType = 'Date | string';
        else if (rf.type === 'object') tsType = 'Record<string, any>';
        else if (rf.type === 'list_text') tsType = 'string[]';
        else if (rf.type === 'list_number') tsType = 'number[]';
        else if (rf.type === 'file') tsType = 'string';
        tsInterfaces += `  ${rf.name}: ${tsType};\n`;
      }
      tsInterfaces += `}\n`;
    } else {
      tsInterfaces += `export interface ${actionNameClean}Response {\n  success: boolean;\n  message?: string;\n}\n`;
    }

    // 2. Generate Server-Side Action Code (SSA)
    let ssaCode = `/**
 * Bubble Plugin Server-Side Action (SSA)
 * Action: ${config.actionName}
 * Target: Bubble Plugin Editor > Actions > ${config.actionName} > Server-side execution
 */

async function(properties, context) {
  // 1. Validation & Input Sanitization
`;

    for (const p of config.parameters.filter(p => p.required)) {
      ssaCode += `  if (properties.${p.name} === undefined || properties.${p.name} === null || properties.${p.name} === '') {\n    throw new Error("[Validation Error] Missing required parameter: '${p.name}'");\n  }\n`;
    }

    ssaCode += `\n  // 2. Prepare Payload\n  const payload = {\n`;
    for (const p of config.parameters) {
      ssaCode += `    ${p.name}: properties.${p.name},\n`;
    }
    ssaCode += `  };\n\n`;

    if (config.useBubbleContextKeys) {
      const keyName = config.bubbleApiKeyName || 'api_key';
      ssaCode += `  // 3. Retrieve Private API Key from Bubble Plugin Context\n`;
      ssaCode += `  const apiKey = context.keys && context.keys["${keyName}"];\n`;
      ssaCode += `  if (!apiKey) {\n    throw new Error("Missing Plugin API Key configuration in Bubble Admin Settings for key '${keyName}'.");\n  }\n\n`;
    }

    if (config.apiUrl) {
      const timeoutMs = config.timeoutMs || 15000;
      const maxRetries = config.enableRetry ? (config.maxRetries || 3) : 1;

      ssaCode += `  // 4. API Request Handler with Timeout & Retry Policies\n`;
      ssaCode += `  const endpoint = "${config.apiUrl}";\n`;
      ssaCode += `  const requestHeaders = {\n`;
      ssaCode += `    "Content-Type": "application/json",\n`;
      if (config.useBubbleContextKeys) {
        ssaCode += `    "Authorization": \`Bearer \${apiKey}\`,\n`;
      }
      if (config.headers) {
        for (const [hk, hv] of Object.entries(config.headers)) {
          ssaCode += `    "${hk}": "${hv}",\n`;
        }
      }
      ssaCode += `  };\n\n`;

      ssaCode += `  async function executeRequest() {\n`;
      ssaCode += `    const controller = new AbortController();\n`;
      ssaCode += `    const timeoutId = setTimeout(() => controller.abort(), ${timeoutMs});\n\n`;
      ssaCode += `    try {\n`;
      ssaCode += `      const response = await fetch(endpoint, {\n`;
      ssaCode += `        method: "${config.httpMethod || 'POST'}",\n`;
      ssaCode += `        headers: requestHeaders,\n`;
      ssaCode += `        body: JSON.stringify(payload),\n`;
      ssaCode += `        signal: controller.signal\n`;
      ssaCode += `      });\n\n`;
      ssaCode += `      clearTimeout(timeoutId);\n\n`;
      ssaCode += `      if (!response.ok) {\n`;
      ssaCode += `        const errorBody = await response.text();\n`;
      ssaCode += `        throw new Error(\`External API responded with HTTP \${response.status}: \${errorBody}\`);\n`;
      ssaCode += `      }\n\n`;
      ssaCode += `      return await response.json();\n`;
      ssaCode += `    } catch (err) {\n`;
      ssaCode += `      clearTimeout(timeoutId);\n`;
      ssaCode += `      if (err.name === 'AbortError') {\n`;
      ssaCode += `        throw new Error("Request timed out after ${timeoutMs}ms");\n`;
      ssaCode += `      }\n`;
      ssaCode += `      throw err;\n`;
      ssaCode += `    }\n`;
      ssaCode += `  }\n\n`;

      if (config.enableRetry) {
        ssaCode += `  // Retry logic with exponential backoff\n`;
        ssaCode += `  let lastError = null;\n`;
        ssaCode += `  let data = null;\n`;
        ssaCode += `  for (let attempt = 1; attempt <= ${maxRetries}; attempt++) {\n`;
        ssaCode += `    try {\n`;
        ssaCode += `      data = await executeRequest();\n`;
        ssaCode += `      break;\n`;
        ssaCode += `    } catch (err) {\n`;
        ssaCode += `      lastError = err;\n`;
        ssaCode += `      console.warn(\`[${config.actionName}] Attempt \${attempt}/${maxRetries} failed: \${err.message}\`);\n`;
        ssaCode += `      if (attempt < ${maxRetries}) {\n`;
        ssaCode += `        await new Promise(res => setTimeout(res, Math.pow(2, attempt) * 200));\n`;
        ssaCode += `      }\n`;
        ssaCode += `    }\n`;
        ssaCode += `  }\n\n`;
        ssaCode += `  if (!data && lastError) {\n`;
        ssaCode += `    throw lastError;\n`;
        ssaCode += `  }\n\n`;
      } else {
        ssaCode += `  const data = await executeRequest();\n\n`;
      }
    } else {
      ssaCode += `  // 3. Process Custom Business Logic\n`;
      ssaCode += `  const data = { status: "success", timestamp: new Date().toISOString() };\n\n`;
    }

    if (config.returnsValue && config.returnFields && config.returnFields.length > 0) {
      ssaCode += `  // 5. Return Mapped Output Fields for Bubble Workflows\n`;
      ssaCode += `  return {\n`;
      for (const rf of config.returnFields) {
        ssaCode += `    ${rf.name}: data.${rf.name} !== undefined ? data.${rf.name} : (properties.${rf.name} || null),\n`;
      }
      ssaCode += `  };\n`;
    } else {
      ssaCode += `  return {\n    success: true,\n    executed_at: new Date().toISOString()\n  };\n`;
    }

    ssaCode += `}\n`;

    // 3. Generate Client-Side Action Code (CSA)
    let csaCode = `/**
 * Bubble Plugin Client-Side Action (CSA)
 * Action: ${config.actionName}
 * Target: Bubble Plugin Editor > Actions > ${config.actionName} > Client-side code
 */

function(properties, context) {
  const actionIdentifier = "${actionNameClean.toLowerCase()}";
  const eventName = \`bubble_plugin_\${actionIdentifier}_completed\`;

  try {
    // 1. Parameter Validation
`;

    for (const p of config.parameters.filter(p => p.required)) {
      csaCode += `    if (properties.${p.name} === undefined || properties.${p.name} === null) {\n      console.error("[Bubble CSA] Missing required parameter '${p.name}' in action '${config.actionName}'");\n      return;\n    }\n`;
    }

    csaCode += `\n    // 2. Client-Side Execution Context\n    const eventDetail = {\n`;
    for (const p of config.parameters) {
      csaCode += `      ${p.name}: properties.${p.name},\n`;
    }
    csaCode += `      triggeredAt: Date.now()\n    };\n\n`;

    csaCode += `    // 3. Dispatch Browser Custom Event\n`;
    csaCode += `    const customEvent = new CustomEvent(eventName, { detail: eventDetail });\n`;
    csaCode += `    window.dispatchEvent(customEvent);\n`;
    csaCode += `    console.log("[Bubble Plugin Action]", eventName, eventDetail);\n\n`;

    csaCode += `    // 4. Trigger JavaScript callback hook if defined on window\n`;
    csaCode += `    if (typeof window[\`on_\${actionIdentifier}\`] === 'function') {\n`;
    csaCode += `      window[\`on_\${actionIdentifier}\`](eventDetail);\n`;
    csaCode += `    }\n`;

    csaCode += `  } catch (clientErr) {\n`;
    csaCode += `    console.error("[Bubble Plugin Action] Client execution error:", clientErr);\n`;
    csaCode += `  }\n`;
    csaCode += `}\n`;

    // 4. Package JSON snippet
    const packageJson = JSON.stringify({
      name: `bubble-plugin-${actionNameClean.toLowerCase()}`,
      version: '1.0.0',
      description: config.description || 'Bubble.io Plugin Action package',
      main: 'index.js',
      scripts: {
        build: 'tsc',
        test: 'jest --coverage',
        lint: 'eslint src/**/*.ts'
      },
      dependencies: {
        axios: '^1.7.9',
        zod: '^3.23.8',
        'p-retry': '^6.2.0'
      },
      devDependencies: {
        typescript: '^5.7.3',
        '@types/node': '^22.13.4',
        jest: '^29.7.0',
        '@types/jest': '^29.5.14'
      }
    }, null, 2);

    return {
      serverSideCode: ssaCode,
      clientSideCode: csaCode,
      typeScriptInterfaces: tsInterfaces,
      packageJsonSnippet: packageJson
    };
  }
}
