export class TemplateScaffolderEngine {
  /**
   * Generates a typed Bubble Server-Side Plugin Action scaffold
   */
  public static scaffoldPluginAction(actionName: string): string {
    const cleanName = actionName.replace(/[^a-zA-Z0-9]/g, '');

    return `/**
 * Bubble.io Server-side Action: ${cleanName}
 * Auto-generated by Bubble Studio
 */

export interface ${cleanName}Properties {
  api_key: string;
  endpoint_url: string;
  payload_json?: string;
  is_sandbox?: boolean;
}

export interface ${cleanName}Context {
  async: (fn: (callback: (err: any, res: any) => void) => void) => any;
  currentUser?: {
    get: (field: string) => any;
  };
}

export interface ${cleanName}Return {
  success: boolean;
  status_code: number;
  response_body: string;
  error_message?: string;
}

export function run_server(
  properties: ${cleanName}Properties,
  context: ${cleanName}Context
): ${cleanName}Return {
  try {
    const payload = properties.payload_json ? JSON.parse(properties.payload_json) : {};
    
    // Bubble context.async wrapper for Node.js async operations
    const result = context.async((callback) => {
      fetch(properties.endpoint_url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': \`Bearer \${properties.api_key}\`
        },
        body: JSON.stringify(payload)
      })
      .then(async (res) => {
        const text = await res.text();
        callback(null, { status: res.status, data: text });
      })
      .catch((err) => callback(err, null));
    });

    return {
      success: result.status >= 200 && result.status < 300,
      status_code: result.status,
      response_body: result.data
    };
  } catch (error: any) {
    return {
      success: false,
      status_code: 500,
      response_body: '',
      error_message: error.message || 'Unknown server-side action error'
    };
  }
}
`;
  }

  /**
   * Generates a TypeScript CRUD API Connector class for a Bubble data type
   */
  public static scaffoldApiConnector(dataTypeName: string): string {
    const typeName = dataTypeName.charAt(0).toUpperCase() + dataTypeName.slice(1);
    const endpointType = dataTypeName.toLowerCase();

    return `/**
 * Bubble.io Data API Client for Type: ${typeName}
 * Auto-generated by Bubble Studio
 */

export interface ${typeName}Record {
  _id: string;
  'Created Date'?: string;
  'Modified Date'?: string;
  [key: string]: any;
}

export interface BubblePaginatedResponse<T> {
  response: {
    cursor: number;
    results: T[];
    remaining: number;
    count: number;
  };
}

export class ${typeName}Connector {
  private baseUrl: string;
  private apiKey: string;

  constructor(appName: string, apiKey: string, isLive: boolean = false) {
    const env = isLive ? '' : '/version-test';
    this.baseUrl = \`https://\${appName}.bubbleapps.io\${env}/api/1.1/obj/${endpointType}\`;
    this.apiKey = apiKey;
  }

  private get headers() {
    return {
      'Authorization': \`Bearer \${this.apiKey}\`,
      'Content-Type': 'application/json'
    };
  }

  /**
   * Fetch paginated records with optional Bubble constraint JSON
   */
  async list(cursor: number = 0, limit: number = 100, constraints?: any[]): Promise<BubblePaginatedResponse<${typeName}Record>> {
    const url = new URL(this.baseUrl);
    url.searchParams.set('cursor', cursor.toString());
    url.searchParams.set('limit', limit.toString());
    if (constraints && constraints.length > 0) {
      url.searchParams.set('constraints', JSON.stringify(constraints));
    }

    const res = await fetch(url.toString(), { headers: this.headers });
    if (!res.ok) throw new Error(\`Bubble Data API error: \${res.statusText}\`);
    return res.json();
  }

  /**
   * Get single record by ID
   */
  async get(id: string): Promise<{ response: ${typeName}Record }> {
    const res = await fetch(\`\${this.baseUrl}/\${id}\`, { headers: this.headers });
    if (!res.ok) throw new Error(\`Bubble Data API error: \${res.statusText}\`);
    return res.json();
  }

  /**
   * Create new record
   */
  async create(data: Partial<${typeName}Record>): Promise<{ status: string; id: string }> {
    const res = await fetch(this.baseUrl, {
      method: 'POST',
      headers: this.headers,
      body: JSON.stringify(data)
    });
    if (!res.ok) throw new Error(\`Bubble Data API creation failed: \${res.statusText}\`);
    return res.json();
  }

  /**
   * Update existing record
   */
  async update(id: string, data: Partial<${typeName}Record>): Promise<{ status: string }> {
    const res = await fetch(\`\${this.baseUrl}/\${id}\`, {
      method: 'PATCH',
      headers: this.headers,
      body: JSON.stringify(data)
    });
    if (!res.ok) throw new Error(\`Bubble Data API update failed: \${res.statusText}\`);
    return res.json();
  }

  /**
   * Delete record
   */
  async delete(id: string): Promise<void> {
    const res = await fetch(\`\${this.baseUrl}/\${id}\`, {
      method: 'DELETE',
      headers: this.headers
    });
    if (!res.ok) throw new Error(\`Bubble Data API deletion failed: \${res.statusText}\`);
  }
}
`;
  }

  /**
   * Generates an Express/Node.js Webhook Receiver for Bubble Data Triggers
   */
  public static scaffoldWebhookReceiver(eventName: string): string {
    return `/**
 * Bubble.io Webhook Receiver: ${eventName}
 * Auto-generated by Bubble Studio
 */

import express, { Request, Response } from 'express';

const app = express();
app.use(express.json());

interface BubbleWebhookPayload {
  event: string;
  app_id: string;
  environment: string;
  data: Record<string, any>;
  timestamp: string;
}

app.post('/webhooks/bubble/${eventName.toLowerCase()}', async (req: Request, res: Response) => {
  try {
    const payload: BubbleWebhookPayload = req.body;
    console.log(\`[Bubble Webhook] Received event '\${payload.event}' for App '\${payload.app_id}'\`);

    // Verify secret signature token if configured
    const authToken = req.headers['x-bubble-secret'];
    if (process.env.BUBBLE_WEBHOOK_SECRET && authToken !== process.env.BUBBLE_WEBHOOK_SECRET) {
      return res.status(401).json({ error: 'Unauthorized webhook trigger' });
    }

    // Business Logic Handling:
    console.log('Record payload:', payload.data);

    // Return 200 to acknowledge receipt to Bubble
    return res.status(200).json({ success: true, receivedAt: new Date().toISOString() });
  } catch (error: any) {
    console.error('[Bubble Webhook Error]', error);
    return res.status(500).json({ error: error.message });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(\`Bubble webhook receiver listening on http://localhost:\${PORT}\`);
});
`;
  }

  /**
   * Generates a fast Type-Safe Bubble SDK Quickstart usage script
   */
  public static scaffoldSdkQuickstart(appName: string): string {
    return `/**
 * Bubble.io Type-Safe SDK Quickstart
 * App: ${appName}
 * Auto-generated by Bubble Studio
 */

import { BubbleTypedApiClient } from './bubbleClient';

async function main() {
  const client = new BubbleTypedApiClient({
    baseUrl: 'https://${appName}.bubbleapps.io',
    apiKey: process.env.BUBBLE_API_KEY || 'YOUR_API_TOKEN',
    version: 'version-test' // or 'live'
  });

  console.log('⚡ Connected to Bubble Data API for ${appName}');

  // 1. Fetch records with constraints
  const usersQuery = new client.UserQuery();
  const result = await usersQuery.list({
    limit: 10,
    constraints: [
      { key: 'authentication.email', constraint_type: 'text contains', value: '@' }
    ]
  });

  console.log(\`Fetched \${result.results.length} users:\`, result.results);

  // 2. Create a new record
  const created = await usersQuery.create({
    email: 'test_user@example.com'
  });
  console.log('Created record ID:', created.id);
}

main().catch(console.error);
`;
  }
}
